apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github-redhat-appstudio.yaml
- group-sync-ci.yaml
- namespaces.yaml
- subscription.yaml
- view-group-sync.yaml
namespace: group-sync-operator
