kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-group-sync
  namespace: group-sync-operator
subjects:
  - kind: User
    name: Michkov
  - kind: User
    name: sbose78
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
