resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/integration-service/config/default?ref=f8e0590af265572ac725e720c06c527dcaa1592e
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/redhat-appstudio/integration-service
  newTag: f8e0590af265572ac725e720c06c527dcaa1592e

namespace: integration-service

patches:
  - ./manager_resources_patch.yaml
